name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: print secret
        env:
          WEIRD_PASSWORD: ${{ secrets.MY_SUPER_SECURE_SECRET}}
        run: echo my secret is $WEIRD_PASSWORD
